### ISSUE TITLE
Error when using with Paragraphs: ArgumentCountError

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/blockreference#9]
Trying to add a `blockreference` field to a Paragraph:

> ArgumentCountError: Too few arguments to function paragraphs_item_access(), 3 passed in /path/modules/blockreference/blockreference.module on line 33 and exactly 4 expected in paragraphs_item_access() (line 170 of /path/modules/paragraphs/paragraphs.module).

Relevant lines:

 - **paragraphs.module**: [L170](https://github.com/backdrop-contrib/paragraphs/blob/1.x-1.x/paragraphs.module#L170)
> function paragraphs_item_access($op, $entity, $account, $entity_type) {

 - **blockreference.module**: [L33](https://github.com/backdrop-contrib/blockreference/blob/1.x-2.x/blockreference.module#L33)
> $entity_access = call_user_func($entity_type . '_access', 'create', $entity_dummy);

**Comment by jenlampton** [comment]
I ran into this issue also. I think it's because the argument order is different between `paragraphs_item_access()` and `entity_access()` so we're not passing the right items.  Block reference assumes these functions all match `entity_access()`. 

```
paragraphs_item_access($op, $entity, $account, $entity_type)
         entity_access($op, $entity_type, $entity, $account)
```
We might be able to fix this by calling `$entity->access()` where all args are guaranteed to be in the same order. I'll give it a try now.

**Comment by yorkshire-pudding** [comment]
While the patch in the HEAD seems to work.  I think this is a cleaner and clearer approach.  Thanks @jenlampton .
